### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by jspicard** [blindsidenetworks/moodle-mod_bigbluebuttonbn#128]
**Reproducible**: Yes

**Steps**:

1. Create a presentation via bigbluebuttonbn plugin in moodle.
2. Join presentation
3. Start recording
4. End recording and log out of room and let video process.
5. No notification is sent

**Issue**:
We're having an issue with recording notifications being sent to users. We are currently using a post publish and post archive script that uses the metadata value bn-recording-status that is created by the bigbluebuttonbn moodle plugin. Looking at the metadata in events.xml for the recording does not show the bn-recording-status metadata that is required to email the students.  I also don't see anywhere to modify the recordingstatus_enabled value in the plugin settings inside of Moodle. I did however see it in the config-dist.php and have attempted to set that in the config.php file as well as modifying the default value in classes/locallib/config.php to true for that setting. Neither of those changes seem to add the bn-recording-status to the metadata being sent to BBB. Is notifications for individual users working in your test system? Any thoughts?

Edited for formatting

**Comment by jfederico** [comment]
That feature was kind of experimental at some point and it has not been updated or even verified since then.
You are right, the only thing you have to do is to set the variable in the config.php file as

$CFG->bigbluebuttonbn['recordingstatus_enabled'] = 1;

either in moodle/config.php or in moodle/mod/bigbluebuttonbn/config.php

The way it works right now though, is to set the meta variable to something like this

<bn-recording-status>
{"email":["\"John Doe\" <jdoe@example.com>"],"context":"http:\/\/web-dev\/moodle36\/mod\/bigbluebuttonbn\/view.php?id=2"}
</bn-recording-status>

But the only email included is the one that belongs to the user who created the meeting. It would not be difficult to change it to something else, but keep in mind that as the parameters are passed as part of the query string, you don't want to make it too long.

Were you using the feature in a previous version?

**Comment by jspicard** [comment]
We were using it with a previous version. I'll be honest, after about 8 hours of investigating and making some small changes in our test environment we were unable to get it working. We haven't touched it since I opened this issue and I went back to make a new recording to copy the metadata that is being sent by the plugin and all of a sudden it's now sending over the information including the students email and the existing ruby script for post archive/publish are now sending the notifications. I'm going to chalk it up to a fluke but I'll let you know if it happens again when we update to BBB 2.2.

Thanks,
Jordan

**Comment by jfederico** [comment]
Yes Please let me know. Now I am curious why was not working. I definitively have to check if it works as intended in the new version. As there is just a few people using this feature, you can be the ones I work with in order to make it work right again.

Cheers

**Comment by jspicard** [comment]
I'll be happy to be the test dummy!

Jordan
