### ISSUE TITLE
Using more than one bbb server

### ISSUE THREAD

**Issue by bilalunalnet** [blindsidenetworks/moodle-mod_bigbluebuttonbn#161]
Hey, thank you for this great plugin. I'm wondering if is it possible to use more than one BigBlueButton server with this plugin?  We are trying to separate our webinars into 2 servers. That would be great if plugin asks which server to use while creating new BBB instance for a course.

**Comment by yvikt** [comment]
Hi, for me it is also very important!
Especially in cases where there is an old and new server, or the performance of one server is not enough.

**Comment by yvikt** [comment]
Or you can just use another server for storing old recordings or backups.

**Comment by jfederico** [comment]
Hey guys. The use cases you are describing have to do with the way your BBB server is deployed. You need a deployment that scales. They are supposed to be handled by a Load Balancer.

This is not going to be added to the plugin.

If you need to scale your deployment you may want to look for a commercial solution instead of self-hosting.
