### ISSUE TITLE
Concurrent join is allowed

### ISSUE THREAD

**Issue by mfarzanegan** [blindsidenetworks/moodle-mod_bigbluebuttonbn#191]
The same user can join the meeting several times, from several devices (by logging in to moodle and click on "Join Session")

I think we need to kick user using id, sessionToken, etc.

is there any way?

**Comment by agtdino** [comment]
Hello mfarzanegan, 

 I've reproduce the problem that the same user can rejoin the meeting by clicking twice or more. The server provide another in  bigbluebutton server userid, and this producing more double users and sound echo and poor the performance in the server bigbluebutton.

 Users be migrating to other solucions other than open source bigbluebutton.  :_(

 My moodle site with 2.8.5+ and  bigbluebutton plugin release 2.1.14  (version 2016051919).

Yes the problem it can be reproduce in my bigbluebutton server 2.2 stable and in the default bigbluebutton server for demo.

Thank's and regards

**Comment by agtdino** [comment]
Maybe you can modify the code of the bigbluebutton module. Verify that the user who clicks on the join the meeting button does not already exist in the meeting.

**Comment by jfederico** [comment]
I am afraid that is and has been the intended behaviour. The integration is not meant to deal BBB capacity constrains. And there are cases where the teacher wants to have two sessions opened. Making it selective would overcomplicate the the implementation because now the plugin would have sync and/or to keep track of what users got in.

It is a nice to have feautre request, but to be honest I  am not seeing this happening in the near future.

Either way, this is not the right place to raise those requests. You can open an issue in JIRA and see if anyone else is interested.

**Comment by omidmaldar** [comment]
Thanks @jfederico  regarding
> now the plugin would have to sync and/or to keep track of what users got in 
 
Perhaps we don't need to keep track of joined users in the plugin side as BBB does this. 
Instead, why can't we simply assign the user id when calling [Join API](https://docs.bigbluebutton.org/dev/api.html#join) and then check the presence of the user via [getMeetingInfo endpoint](https://docs.bigbluebutton.org/dev/api.html#getmeetinginfo) as it returns the list of attendees including the user id we have already set for them? Anyway, this a known user for the plugin. 

The doc also says: user id is `An identifier for this user that will help your application to identify which person this is. This user ID will be returned for this user in the getMeetingInfo API call so that you can check`

I'm also wondering if this feature is already requested on JIRA. Can someone share a link to the JIRA, please?
