### ISSUE TITLE
preupload presentation more than one document

### ISSUE THREAD

**Issue by runout-at** [blindsidenetworks/moodle-mod_bigbluebuttonbn#199]
Teachers should be able to upload more than one document in the field `Presentation content`

Currently there is a restriction to one document and no possibility to change this in the settings.
(I see: `Maximum file size: Unlimited, maximum number of files: 1`)

This would be useful to preupload multiple documents before starting the session. teachers with low internet bandwidth experience problems when uploading documents during the session.

**Comment by jfederico** [comment]
Hi @runout-at 
Yeah, that is something I have wanted to do since long long time ago. The issue is that, although BBB can receive and manage multiple documents at once, it is not able to prioritize which document will be the one shown by default. It would be the first one to be processed and even that may be random.

The other thing is that you won't save much badwidht either because BBB has to pull the files from Moodle anyways. There have been discussions during BBB summits on how to tacke the multipresentation issue, but nothing definitive yet.

So, until we have it on BBB, this feature request is blocked.

**Comment by runout-at** [comment]
BBB and moodle are both on servers and bandwidth should not be any problem between servers.

uploading and converting the presentation during the session makes the whole party waiting for it to finish. on preupload this can take place before or at the beginning of the session and will not interrupt the flow of the session later on.

if bbb can not prioritize a document nor sort those by name,... (which would be the desired behaviour), i'd like to have it anyways as the teacher could select the right document  at the beginning of the session. There could just be a hint on the upload form about this problem so people know what will happen if they upload more than one document.

but you are right, this should be changed in bbb too.

**Comment by jfederico** [comment]
Yeah, what you are not considering is that the bottle neck is not really in the upload. Of course it may be, if your teacher is in a really low bandwidh network. But the main issue here is the processing part. It depends of many factors as the size of the presentation, how busy BBB is at the time the presentation was uploaded, if there were other presentations being processed for other meetings, etc.

One of the ideas we have discussed is to decouple the component that process the presentation to an external service and even to cache the processed files using md5 so BBB does not have to wait or if it does, you can have some indication in the client.

Otherwise you have a teacher who "pre-uploaded" a presentation (or a bnunch of them), with a blank screen that last for 5 minutes, while waiting for the files to be converted. Which make them think that the plugin or BBB are broken. Which means a ticket to their IT department, and an issue opened here from them for a bug that is not really :D

So, believe me, neither you or me want to go that road ;)

It is a legit use case though. As I said, I had that in mind since the preuploaded presentation was implemented. But it is pending for when the feature is extended in BBB.
