### ISSUE TITLE
Pick BBB UI language from Moodle user profile language instead of preferred browser language

### ISSUE THREAD

**Issue by abias** [blindsidenetworks/moodle-mod_bigbluebuttonbn#205]
According to the BBB documentation and according to my tests, the BBB UI language is chosen based on the preferred browser language.

For the Moodle integration of BBB, I would like to propose to pick the BBB UI language based on the Moodle user profile language instead.

This will help users who are working on a computer which does not have their main language as browser language set, but who have set the right language in their Moodle user profile.

As always, this should be configurable with an admin setting to support the existing as well as the new behaviour.

**Comment by jfederico** [comment]
I misread this request. I thought you were talking about the plugin itself since this is the plugin repo.

It is actually not possible to tell BBB what language to use, so this feature request would have to be considered until the BBB API is  extended.

But good point, I will raise your concern to the HTML5 team and advocate to hav it as part of 2.3 :smile:

**Comment by jfederico** [comment]
The development is tracked on [Moodle Tracker as CONTRIB-8176](https://tracker.moodle.org/browse/CONTRIB-8176)
