### ISSUE TITLE
Missing Presentation Slides when Restarting BigBlueButton Session too Quickly

### ISSUE THREAD

**Issue by steffen-moser** [blindsidenetworks/moodle-mod_bigbluebuttonbn#271]
### Preconditions:

  - BigBlueButton activity (2.3.3, Build: 2019042008) in Moodle (3.8.2+, Build: 20200327), but older versions of Moodle are also affected.
  - In the a course's moodle activity, a file containing presentation slides (e.g. PDF) is deposited.

### Problem:

When the first user (e.g. a course instructor and moderator in BBB) starts the BBB meeting, all is fine. Then, the user ends the meeting in BBB. In this case, the user is guided back to the BBB activity page in Moodle. Moodle or the BBB activity in Moodle assume for a short amount of time that the meeting was still running. If a user then rejoins (or let's better say: recreates) the meeting, it will show an empty presentation. According to BBB's "/var/log/bigbluebutton/bbb-web.log", BBB is unable to access the referenced presentation file in the case of this second startup of the meeting:

`
2020-07-15T18:00:25.126+02:00 ERROR o.b.p.PresentationUrlDownloadService - Invalid HTTP response=[404] for url=[https://polaris.informatik.uni-ulm.de/moodle/pluginfile.php/1/mod_bigbluebuttonbn/presentationdefault/3a685e2696b35daa7551e840e00217ae/default.pdf] with meeting[ab408f1631bbcbba2695b1ad07447c565ef98eb1-1594828824941]
2020-07-15T18:00:25.127+02:00 ERROR o.b.web.controllers.ApiController - Failed to download presentation=[https://polaris.informatik.uni-ulm.de/moodle/pluginfile.php/1/mod_bigbluebuttonbn/presentationdefault/3a685e2696b35daa7551e840e00217ae/default.pdf], meeting=[ab408f1631bbcbba2695b1ad07447c565ef98eb1-1594828824941], fileName=[null]
2020-07-15T18:00:30.131+02:00 ERROR o.b.p.DocumentConversionServiceImp - Presentation upload failed for meetingId=ab408f1631bbcbba2695b1ad07447c565ef98eb1-1594828824941 presId=d2d9a672040fbde2a47a10bf6c37b6a4b5ae187f-1594828825037
2020-07-15T18:00:30.131+02:00 ERROR o.b.p.DocumentConversionServiceImp - Presentation upload fail reasons [failed_to_download_file]
`

Despite of the fact that the user's behavior looks a bit far fetched, we do see this error several times a day and we also have sporadic reports of users that meetings start without presentation slides. Maybe users have a problem with connecting their headset or camera, end the meeting and start it afterward for a second time. Maybe a user's browser doesn't reload the activity's page due to network issues. 

### Expected behavior:

The presentation deposited in Moodle's BBB activity should be always shown in BBB. It should not depend on the number of times and the frequency of having a user entering and exiting a BBB session.

### Assumed error:

According to "bbb-web.log" in BBB, Moodle seems to withdraw the permissions for accessing the presentation slides when the meeting has started for the first time (maybe after the first access of the file by BBB?). When restarting a BBB meeting very quickly, the BBB activity in Moodle hasn't switched to the state "meeting is not running", yet. Only when being in this state, the slides are made available again for being downloaded by BBB. For this reason, BBB cannot access the slides.

**Comment by jfederico** [comment]
Thanks for the report @steffen-moser. Very well documented. I would encourage you to open these cases on JIRA though. Soon this space will be closed and there will be no more follow up though github. We have been using JIRA since probably 6 years ago.

This is an odd case though. This is what happens

User (anyone who is able to join) click the Join button -> BBB meeting is created passing the presentation URL -> New tab is open -> User is redirected to BBB

At this point it doesn't matter if the user has troubles joining video. BBB should try to pull the presentation.

In Moodle, the BBB plugin opens a onetime access to the file in question so BBB can pull it whitout credentials. But, it would only be closed only closed if BBB (or some other app) tries to use the link (the second case could happen, but it is very unlikely as all this is done -hopefully- in milliseconds).

If for any reason such as audio or connectivity problems, the user has to leave the tab with BBB on, and BBB closes the session after detecting no one was there, all the references were gone. Meaning the next time the user clicks the button, the full flow described is followed again (click -> create -> onetime link -> join etc)

What I am thinking is that there may be an issue not in the plugin, but in BBB after the updates to the presentation. I am going to report this to the guy who is working on that specific component and see what he has to say.

What version of BBB do you have?

**Comment by steffen-moser** [comment]
Thank you for the very fast reply, @jfederico. Next time I'll use JIRA. I was not aware that Github is not the correct platform for reporting issues. 

I can reproduce the problem on two BBB platforms: The first one is a single-host BBB worker running BBB 2.2.20. The other one is a larger BBB cloud with 20 worker servers (BBB 2.2.19) and a Scalelite load balancer.  

I am quite sure that this problem is related to the "onetime access" thing. It seems to me that the user has to wait for at least a few seconds until the activities site gets refreshed. If he or she clicks faster (while the activity still reports that a meeting is running), it seems that the onetime link is not regenerated. As the BBB meeting has been ended previously, BBB has no chance to reget the presentation and is asked to download from an expired link in the API create call. In this case, BBB shows a blank presentation, it even does not fall back to the default which is deposited in BBB itself.

Maybe, I am not sure yet, it takes even a few more seconds when Scalelite is between Moodle and BBB to inform Moodle about an ended meeting, but I definitely see this problem on both, the single-host BBB platform and the large Scalelite-balanced BBB instance. Nevertheless, I have the impression that in the Scalelite instance, I see it more often.

If you wish, I can provide a screencast showing the problem by tomorrow.

**Comment by steffen-moser** [comment]
See also: https://tracker.moodle.org/browse/CONTRIB-8538
