### ISSUE TITLE
Privileges are not transferred to BBB

### ISSUE THREAD

**Issue by proedie** [blindsidenetworks/moodle-mod_bigbluebuttonbn#370]
Hi

We have a little problem with privileges with our Moodle/BBB combo.

- When restoring a BBB activity from a backup, teaches are not moderators in BBB.
- If we create a new BBB activity teaches are moderators.
- If we then add a new teacher to the class, the new teacher will not be a moderator in BBB.

Are we missing some setting or is there a problem?

We are currently using Moodle 3.10.3+ and BBB plugin 2.4-beta. I'm not sure where to find the version of BBB itself. Does 1157 make sense?

Thank you very much in advance.

**Comment by jfederico** [comment]
By default, Moderator is only the user who creates the Activity. Everybody else is Viewer. (It has been like this since v2.1).

You can match the Moodle roles with BBB roles using the participant list (per activity), and also, you can set up the matching role by default at the site level using the plugin settings.

Just keep in mind that the defaults will only affect the newly created activities.

Any user with Editing capabilities in the course can actually make this change (Teachers for example).
