### ISSUE TITLE
Fix plugin compatibility in Totara 13+

### ISSUE THREAD

**Issue by simoncoggins** [blindsidenetworks/moodle-mod_bigbluebuttonbn#403]
Our customers have reported that they are unable to configure instances of this plugin in versions of Totara after 13.0. We've investigated and found that it is because of some security hardening which we did to Totara which cleans HTML from static moodleform elements (totara issue ID: TL-20800).

The solution is to whitelist specific uses in code that aren't at risk of XSS (as is the case here) by calling a special method.

Because the method is Totara specific there needs to be a check to ensure compatibility with Moodle so the plugin can continue to work as before.

I've attached a patch file which fixes the issue for Totara while maintaining Moodle compatibility, would you consider including it in your next release?

[0001-Fix-compatibility-of-big-blue-button-in-Totara-13.patch.gz](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/files/6693562/0001-Fix-compatibility-of-big-blue-button-in-Totara-13.patch.gz)

**Comment by simoncoggins** [comment]
Ah I just had a look on the master branch and it looks like you rewrote the JS recently which changed this file significantly - I will need to rework my patch to make it apply. I'll look at opening a pull request with a new proposed change as soon as I can.

**Comment by jfederico** [comment]
@simoncoggins  Yeah, the issue is that we no longer have access to Totara code. This has been the case for the last 2 or so years. And at this point neither the bandwidth to keep supporting it.

As the plugin is being refactored and the two projects diverge more and more, it is becoming more difficult to guarantee the compatibility. Perhaps the best bet will be to fork the code for Totara in one of the older versions. 

Can you tell what is the last version that worked with Totara?

**Comment by simoncoggins** [comment]
Just wanted to note that the PR fixing this issue in v2.4 has now been merged, so I'm closing this ticket.
