### ISSUE TITLE
invite users not registered in moodle (Feature request)

### ISSUE THREAD

**Issue by amg-web** [blindsidenetworks/moodle-mod_bigbluebuttonbn#534]
invite users not registered in moodle like Greenlight do eg via link in Moderator only message.

**Comment by jfederico** [comment]
Thanks for the feature suggestion/request. But there are a few things to consider:

1. Since this plugin is merged into Moodle core, version 2.4 is frozen for features and enhancements. Only bug fixes and security patches are being considered at this point.
2. Feature request must be done through Moodle Tracking System following Moodle rules for documenting the request.
3. Accepting or rejecting a request, same as scheduling its development is now done following Moodle development process.

And yet, this is a good feature to have. If you don't mind, I would encourage you to open an issue in https://tracker.moodle.org/projects/MDL/issues/

When opening an issue you should do it following Moodle rules https://docs.moodle.org/dev/Tracker_introduction.
