### ISSUE TITLE
Plugin-level scaling solution

### ISSUE THREAD

**Issue by sajadkhosravani1** [blindsidenetworks/moodle-mod_bigbluebuttonbn#536]
Despite the fact that scalelite provides a fairly suitable scaling solution, some organizations have been observed which prefer a scalable plugin that connects to more than one server rather than one scaled server. This may be due to factors such as scalelite's expertise-requirement to deploy.

**Comment by hostbbb** [comment]
How does getRecordings know what server to fetch recording on?  If you have a weekly meeting is the meeting always on the same server? or deos getRecordings need to always check all servers for the existance on match.

**Comment by sajadkhosravani1** [comment]
Please take a look at the [provided soloution](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/pull/537) if you already didn't.
In this solution, each instance of bigbluebuttonbn is assigned to one single server. Besides, Since the bigbluebuttonbn_unique_meetingid_seed function (from locallib.php) makes sure that meeting-ids are unique, having the meeting-id, you can simply retrieve the bigbluebuttonbn instance and get the assigned server.
Furthermore, a brief glance at the performed modifications within the bigbluebuttonbn_get_recordings_array_fetch_page function, [here](https://github.com/blindsidenetworks/moodle-mod_bigbluebuttonbn/pull/537/commits/50952520113ac8d1654d60f0ba6e4e7e9b400329#diff-3494b45596f0f648d894a5f22070eaae01f3e0ea664be0430b8d23eb7d93e35a), will eliminate the rest of your related gray areas.

**Comment by jfederico** [comment]
Thanks for the feature suggestion/request. But there are a few things to consider:

1. Since this plugin is merged into Moodle core, version 2.4 is frozen for features and enhancements. Only bug fixes and security patches are being considered at this point.
2. Feature request must be done through Moodle Tracking System following Moodle rules for documenting the request.
3. Accepting or rejecting a request, same as scheduling its development is now done following Moodle development process.

Now, regardless, here is my comment:

This would add complexity to to plugin not only in terms of code, but in terms of administration once deployed. I understand the use case those who want this implementation done want to cover, but this definitely should be delegated to a Load Balancer solution such as Scalelite (or any other that suits particular needs).

At this point, I think you are better of by keep using your fork.
