### ISSUE TITLE
Share meeting over different courses

### ISSUE THREAD

**Issue by Kloenk** [blindsidenetworks/moodle-mod_bigbluebuttonbn#542]
Users are requiring one shared meeting over several courses. As this meeting is the only shared activity over all courses groups are not suitable, therefore sharing only the meeting would be the optimal solution.
Sharingcart does not work for this.

**Comment by jfederico** [comment]
Thanks for the feature suggestion/request. But there are a few things to consider:

1. Since this plugin is merged into Moodle core, version 2.4 is frozen for features and enhancements. Only bug fixes and security patches are being considered at this point.
2. Feature request must be done through Moodle Tracking System following Moodle rules for documenting the request.
3. Accepting or rejecting a request, same as scheduling its development is now done following Moodle development process.

And yet, this is a good feature to have. If you don't mind, I would encourage you to open an issue in https://tracker.moodle.org/projects/MDL/issues/
